function [fitresult, gof] = determine_birefringence_fit(f, beta,norder)
    %CREATEFIT(X,Y)
    %  Create a fit.
    %
    %  Data for 'untitled fit 1' fit:
    %      X Input: x
    %      Y Output: y
    %  Output:
    %      fitresult : a fit object representing the fit.
    %      gof : structure with goodness-of fit info.
    %
    %  See also FIT, CFIT, SFIT.
    
    %  Auto-generated by MATLAB on 19-Feb-2024 18:36:36
    if nargin==2
        norder = 2;
    end
    display(norder);
    
    %% Fit: 'untitled fit 1'.
    
    [xData, yData] = prepareCurveData( f, beta );
    
    % Set up fittype and options.
    if norder==3
        ft = fittype( 'poly3' );
    else
        ft = fittype( 'poly2' );
    end
    
    % Fit model to data.
    [fitresult, gof] = fit( xData, yData, ft, 'Normalize', 'off' );
    
    % % Plot fit with data.
    % figure( 'Name', 'untitled fit 1' );
    % h = plot( fitresult, xData, yData );
    % legend( h, 'y vs. x', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
    % % Label axes
    % xlabel( 'x', 'Interpreter', 'none' );
    % ylabel( 'y', 'Interpreter', 'none' );
    % grid on


